const KEY = "mars_ai_game_v2_state";

const defaultState = {
  coins:1250,gems:85,xp:420,level:4,streak:3,referrals:2,missionsDone:1,claimedDaily:false,
  owned:{characters:["Raven"],cars:["Apex GT"]},
  equipped:{character:"Raven",car:"Apex GT"},rank:"Bronze I",
  controlScheme:localStorage.getItem("mars_control_scheme")||"standard",sound:true,music:true,
  stats:{wins:0,losses:0,matches:0,bestScore:0}
};
let state;
try{state=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaultState)}catch(e){state=structuredClone(defaultState)}
state.stats ||= structuredClone(defaultState.stats);
state.controlScheme ||= "standard"; state.sound=state.sound!==false; state.music=state.music!==false;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const screen=document.getElementById("screen");

const games={
 competitive:{icon:"🪖",title:"Iron Front: Reckoning",desc:"Competitive AI combat with tactical squads and multiple battle modes.",type:"combat",modes:[
  ["br","Battle Royale","50 combatants • You + 3 AI teammates"],["cs","Clash Squad","4v4 • round-based tactical combat"],["lw","Lone Wolf","1v1 or 2v2 • fast close combat"],["tdm","Team Deathmatch","4v4 • first team to the target"],["dom","Domination","4v4 • capture and hold objectives"],["snd","Search & Destroy","4v4 • attack and defend"],["survival","Survival","Squad vs increasingly difficult AI waves"],["gun","Gun Game","Progress through a weapon ladder"],["sniper","Sniper Arena","1v1 or 2v2 precision combat"]]},
 racing:{icon:"🏎️",title:"Velocity Rush",desc:"Race AI drivers, build your garage and chase records.",type:"racing",modes:[
  ["normal","Normal Race","8 total • You + 7 AI"],["police","Police Chase","Escape the pursuing AI police"],["street","Street Race","Point-to-point city competition"],["time","Time Trial","Beat the target time"],["elim","Elimination","Last-place racer is removed each stage"],["drift","Drift Challenge","Score points with controlled drifting"]]},
 runner:{icon:"🏃",title:"Neon Run",desc:"Fast obstacle action with records, upgrades and AI challenges.",type:"runner",modes:[
  ["endless","Endless Run","Survive as long as possible"],["time","Time Run","Finish before the clock expires"],["obstacle","Obstacle Rush","Clear increasingly difficult obstacles"],["coin","Coin Rush","Collect while surviving hazards"],["boss","Boss Run","Survive special challenge sections"]]},
 fighter:{icon:"🥊",title:"Warborn Arena",desc:"Close-combat battles, tournaments and boss encounters.",type:"fighter",modes:[
  ["story","Story Fight","Progress through AI opponents"],["tournament","Tournament","Fight through a bracket"],["duel","1v1 Arena","One fighter versus one AI"],["survival","Survival","Defeat successive opponents"],["boss","Boss Fight","Face a powerful AI opponent"],["training","Training","Learn attacks and combos"]]},
 moto:{icon:"🏍️",title:"Moto Rush",desc:"High-speed motorcycle competition.",type:"racing",modes:[
  ["race","Normal Race","You + AI riders"],["traffic","Traffic Rush","Ride through dense traffic"],["police","Police Escape","Outrun AI police"],["time","Time Trial","Beat the clock"],["stunt","Stunt Run","Score through risky stunts"]]},
 hunt:{icon:"🏹",title:"Survival Hunt",desc:"Explore, survive and complete AI-driven field missions.",type:"hunt",modes:[
  ["wilderness","Wilderness Survival","Manage threats and resources"],["hunt","Hunt","Track AI targets"],["resource","Resource Run","Gather and reach extraction"],["night","Night Survival","Survive the night"],["rescue","Rescue Mission","Locate and protect targets"]]},
 football:{icon:"⚽",title:"Street Football",desc:"Small-sided football against AI teams.",type:"sports",modes:[
  ["1v1","1v1","Quick street duel"],["2v2","2v2","You + AI teammate vs AI duo"],["3v3","3v3","Small-sided team match"],["penalty","Penalty Shootout","Pressure finishing"],["skill","Skill Challenge","Timed technical challenge"]]},
 hoops:{icon:"🏀",title:"Street Hoops",desc:"Fast basketball challenges against AI.",type:"sports",modes:[
  ["1v1","1v1","One-on-one"],["2v2","2v2","Team play"],["3v3","3v3","Half-court competition"],["shootout","Shootout","Timed shooting"],["time","Time Challenge","Score before time runs out"]]},
 tactical:{icon:"🎯",title:"Tactical Strike",desc:"Objective-based tactical missions powered by AI.",type:"hunt",modes:[
  ["mission","Tactical Mission","Complete the objective"],["defense","Defense","Hold the position"],["escort","Escort","Protect the target"],["elimination","Elimination","Clear hostile AI"],["survival","Survival","Hold out under pressure"]]},
 archery:{icon:"🏹",title:"Archery Arena",desc:"Precision shooting and competitive AI challenges.",type:"hunt",modes:[
  ["target","Target Practice","Accuracy training"],["time","Time Challenge","Score before time expires"],["duel","AI Duel","Precision versus AI"],["range","Long Range","Distance accuracy"],["tournament","Tournament","Progress through rounds"]]}
};
const gameOrder=["competitive","racing","runner","fighter","moto","hunt","football","hoops","tactical","archery"];

function nav(route,extra=""){history.pushState({route},"","#"+route+(extra?"/"+extra:""));render(route,extra)}
function back(){history.back()}
window.addEventListener("popstate",()=>{const p=location.hash.slice(1).split("/");render(p[0]||"home",p[1]||"")});
function money(){return `<div class="currency"><div class="money">🪙 <b>${state.coins.toLocaleString()}</b><span>Coins</span></div><div class="money">💎 <b>${state.gems.toLocaleString()}</b><span>Gems</span></div></div>`}
function gameCard(k){const g=games[k];return `<div class="card game-card"><div><div class="game-icon">${g.icon}</div><h3>${g.title}</h3><p>${g.desc}</p></div><button class="button" data-game="${k}">Open Lobby</button></div>`}
function layout(title,body){return `<div class="back"><button class="button secondary" data-action="back">← Back</button></div><h2>${title}</h2>${body}`}
function home(){return `<section class="hero"><p class="muted">WELCOME BACK</p><h1>Ready to play?</h1><p class="muted">Your Mars AI game hub.</p>${money()}<div class="two-col"><button class="button" data-route="games">🎮 PLAY</button><button class="button secondary" data-route="earn">🪙 EARN</button></div></section><section class="featured"><div class="tag">FEATURED GAME</div><h2>🪖 IRON FRONT: RECKONING</h2><p>Competitive AI combat. Train, choose your mode and enter the fight.</p><button class="button" data-game="competitive">Enter Combat Lobby</button></section><div class="section-title"><h2>Quick Access</h2></div><div class="grid"><div class="card"><h3>🎯 Missions</h3><p>Complete objectives and earn rewards.</p><button class="button" data-route="missions">Open</button></div><div class="card"><h3>🎁 Rewards</h3><p>Daily and event rewards.</p><button class="button" data-route="rewards">Open</button></div><div class="card"><h3>🛒 Store</h3><p>Spend Coins and Gems.</p><button class="button" data-route="shop">Open</button></div><div class="card"><h3>🏆 Rank</h3><p>${state.rank} • Level ${state.level}</p><button class="button" data-route="leaderboard">Open</button></div></div>`}
function gamesPage(){return layout("🎮 Game Hub",`<div class="notice">Choose a game to enter its dedicated lobby. Every listed game now has a playable arcade engine, touch controls, sound and AI.</div><div class="grid">${gameOrder.map(gameCard).join("")}</div>`)}
function gameLobby(k){const g=games[k];let extra="";if(k==="racing"||k==="moto")extra=`<div class="section-title"><h2>Garage</h2></div><div class="card"><h3>${k==="moto"?"🏍️":"🚗"} ${state.equipped.car}</h3><p>${state.owned.cars.length} vehicle(s) owned. Buy and equip vehicles from your garage.</p><button class="button" data-route="garage">Open Garage</button></div>`;if(k==="competitive")extra=`<div class="section-title"><h2>Combat Hub</h2></div><div class="grid"><div class="card"><h3>🪖 Character</h3><p>${state.equipped.character} equipped</p></div><div class="card"><h3>🔫 Loadout</h3><p>Weapons, armor, Gloo Wall and equipment are active in the match engine.</p></div><div class="card"><h3>🏋️ Training Ground</h3><p>Learn movement, aim, shooting, healing and controls.</p><button class="button" data-mode="training">Train</button></div><div class="card"><h3>🎛️ Controls</h3><p>Choose Standard, Advanced or Custom touch controls.</p><button class="button secondary" data-route="controls">Configure</button></div></div>`;return layout(`${g.icon} ${g.title}`,`<div class="hero"><h1>Game Lobby</h1><p class="muted">${g.desc}</p>${money()}</div>${extra}<div class="section-title"><h2>Modes</h2></div><div class="grid">${g.modes.map(m=>`<div class="card mode-card"><h3>${m[1]}</h3><small>${m[2]}</small><button class="button" data-mode="${m[0]}" data-game-mode="${k}">Play</button></div>`).join("")}</div>`)}
function modePreview(k,m){const g=games[k],mode=g.modes.find(x=>x[0]===m)||[m,m,""];return layout(`${g.icon} ${mode[1]}`,`<div class="hero"><p class="pill">${g.title}</p><h1>${mode[1]}</h1><p class="muted">${mode[2]}</p><div class="stat-grid"><div class="stat"><b>${k==="competitive"&&m==="br"?"50":"AI"}</b><span>Participants</span></div><div class="stat"><b>200</b><span>Base HP</span></div><div class="stat"><b>🎮</b><span>Touch Ready</span></div></div><button class="button" data-start="${k}/${m}">START MATCH</button></div><div class="notice">Playable engine enabled. Use the on-screen controls or keyboard. Sound can be toggled from the match HUD.</div>`)}
function missions(){return layout("🎯 Missions",`<div class="list"><div class="row"><div><b>Play a game</b><div class="muted">Complete a match or training activity</div></div><span class="pill">${state.missionsDone}/1</span></div><div class="row"><div><b>Keep your streak</b><div class="muted">Current streak</div></div><span class="pill">${state.streak} days</span></div></div>`)}
function rewards(){return layout("🎁 Rewards",`<div class="hero"><h1>Daily Reward</h1><p class="muted">${state.claimedDaily?"Already claimed today.":"Claim your daily reward."}</p><button class="button" data-daily ${state.claimedDaily?"disabled":""}>${state.claimedDaily?"Claimed":"Claim +100 Coins"}</button></div>`)}
function earn(){return layout("🪙 Earn Coins",`<div class="hero"><h1>Coin Center</h1><p class="muted">Permanent account Coins are earned here and through game activities. They are separate from temporary match credits.</p>${money()}</div><div class="grid"><div class="card"><h3>🎯 Daily Missions</h3><p>Complete objectives to earn Coins.</p></div><div class="card"><h3>🔥 Streaks</h3><p>Maintain activity streaks for bonuses.</p></div><div class="card"><h3>🏆 Milestones</h3><p>Progress milestones award Coins.</p></div><div class="card"><h3>🎪 Events</h3><p>Limited-time Coin opportunities.</p></div></div>`)}
function leaderboard(){return layout("🏆 Rank",`<div class="hero"><h1>${state.rank}</h1><p class="muted">Level ${state.level} • ${state.xp} XP</p></div><div class="list">${["You","AI Vanguard","AI Sentinel","AI Phantom","AI Titan"].map((n,i)=>`<div class="row"><b>#${i+1} ${n}</b><span>${Math.max(100,state.xp-i*55)} pts</span></div>`).join("")}</div>`)}
function profile(){return layout("👤 Profile",`<div class="hero"><h1>Player Profile</h1><p class="muted">Your local game profile is active. Telegram account linking can replace the local identity when a backend is connected.</p>${money()}<div class="stat-grid"><div class="stat"><b>${state.level}</b><span>Level</span></div><div class="stat"><b>${state.streak}</b><span>Streak</span></div><div class="stat"><b>${state.referrals}</b><span>Referrals</span></div><div class="stat"><b>${state.stats.wins}</b><span>Wins</span></div></div></div><div class="grid"><div class="card"><h3>🪖 Character</h3><p>${state.equipped.character}</p></div><div class="card"><h3>🏎️ Vehicle</h3><p>${state.equipped.car}</p></div><div class="card"><h3>🔊 Audio</h3><p>Sound: ${state.sound?"ON":"OFF"} • Music: ${state.music?"ON":"OFF"}</p><button class="button secondary" data-toggle-sound>Toggle Sound</button></div></div>`)}
function shop(){return layout("🛒 Store",`<div class="notice">Permanent Coins and Gems are used for account purchases. Match credits are separate.</div><div class="grid"><div class="card"><h3>🪖 Character</h3><p>Premium character unlock.</p><button class="button" data-buy="character">Buy • 500 Coins</button></div><div class="card"><h3>🏎️ Car</h3><p>Garage vehicle.</p><button class="button" data-buy="car">Buy • 800 Coins</button></div><div class="card"><h3>💎 Premium Item</h3><p>Special cosmetic.</p><button class="button" data-gem-buy>Buy • 50 Gems</button></div></div>`)}
function garage(){return layout("🏎️ Garage",`<div class="hero"><h1>${state.equipped.car}</h1><p class="muted">Equip any vehicle you own.</p></div><div class="list">${state.owned.cars.map(c=>`<div class="row"><b>🚗 ${c}</b><button class="button secondary" data-equip-car="${c}">${state.equipped.car===c?"Equipped":"Equip"}</button></div>`).join("")}</div><button class="button" data-route="shop">Buy Vehicles</button>`)}
function controls(){return layout("🎛️ Controls",`<div class="notice">Touch controls are used in every playable match. Custom mode uses the compact HUD layout; keyboard controls remain available on desktop.</div><div class="grid"><div class="card"><h3>Standard</h3><p>Movement + action buttons.</p><button class="button" data-control="standard">Select</button></div><div class="card"><h3>Advanced</h3><p>More direct aim/action control.</p><button class="button" data-control="advanced">Select</button></div><div class="card"><h3>Custom</h3><p>Compact HUD layout.</p><button class="button" data-control="custom">Select</button></div></div>`)}

let activeGame=null,audioCtx=null,musicTimer=null;
function ensureAudio(){if(!state.sound&&!state.music)return null;try{audioCtx ||= new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}catch(e){return null}}
function beep(freq=440,duration=.08,type="sine",volume=.035){if(!state.sound)return;const ctx=ensureAudio();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)}
function startMusic(){if(!state.music||musicTimer)return;const n=[196,247,294,247];let i=0;musicTimer=setInterval(()=>{if(state.music)beep(n[i++%n.length],.12,"triangle",.012)},520)}
function stopMusic(){if(musicTimer)clearInterval(musicTimer);musicTimer=null}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function matchShell(g,mode){screen.innerHTML=`<div id="matchRoot" class="match-root"><div class="match-top"><button id="quitMatch" class="match-btn">← Lobby</button><div><b>${g.icon} ${esc(g.title)}</b><small>${esc(mode[1])}</small></div><button id="soundMatch" class="match-btn">${state.sound?"🔊":"🔇"}</button></div><div class="match-hud"><div id="matchStats">Loading...</div></div><canvas id="gameCanvas"></canvas><div id="matchMessage" class="match-message"></div><div id="touchControls" class="touch-controls"></div></div><style>.match-root{position:fixed;inset:0;z-index:9999;background:#070a10;color:#fff;display:flex;flex-direction:column;font-family:inherit}.match-top{height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 10px;background:#101520;border-bottom:1px solid #293044;gap:8px}.match-top>div{text-align:center;flex:1;display:flex;flex-direction:column}.match-top small{opacity:.65;margin-top:2px}.match-btn{background:#1a2130;color:#fff;border:1px solid #35405a;border-radius:12px;padding:10px 13px;font-weight:700}.match-hud{position:absolute;z-index:3;left:10px;right:10px;top:68px;pointer-events:none}.match-hud>div{display:inline-block;background:rgba(10,14,24,.78);padding:8px 11px;border-radius:12px;border:1px solid #30394e;font-size:13px}#gameCanvas{width:100%;height:100%;min-height:0;display:block;touch-action:none}.match-message{position:absolute;z-index:4;top:48%;left:50%;transform:translate(-50%,-50%);text-align:center;font-size:25px;font-weight:900;text-shadow:0 2px 10px #000;pointer-events:none}.touch-controls{position:absolute;z-index:5;left:0;right:0;bottom:18px;height:150px;pointer-events:none}.tc{position:absolute;width:58px;height:58px;border-radius:50%;border:1px solid #7d8aa8;background:rgba(20,27,42,.78);color:#fff;font-size:22px;font-weight:900;pointer-events:auto;touch-action:none}.tc:active{transform:scale(.94);background:#303b58}.tc.up{left:78px;bottom:62px}.tc.left{left:15px;bottom:0}.tc.down{left:78px;bottom:0}.tc.right{left:141px;bottom:0}.tc.a{right:18px;bottom:62px}.tc.b{right:84px;bottom:0}.tc.c{right:18px;bottom:0}@media(min-width:800px){.touch-controls{opacity:.55}.tc{width:50px;height:50px}}</style>`;return{canvas:document.getElementById("gameCanvas"),stats:document.getElementById("matchStats"),controls:document.getElementById("touchControls")}}
function setupControls(type,input){const c=input.controls;c.innerHTML=`<button class="tc up" data-key="up">▲</button><button class="tc left" data-key="left">◀</button><button class="tc down" data-key="down">▼</button><button class="tc right" data-key="right">▶</button><button class="tc a" data-key="a">${type==="racing"?"⚡":type==="runner"?"⬆":"A"}</button><button class="tc b" data-key="b">B</button><button class="tc c" data-key="c">${type==="fighter"?"🛡️":"🎯"}</button>`;const keys=new Set(),map={ArrowUp:"up",w:"up",W:"up",ArrowLeft:"left",a:"left",A:"left",ArrowDown:"down",s:"down",S:"down",ArrowRight:"right",d:"right",D:"right"," ":"a",e:"b",E:"b",q:"c",Q:"c"};window.addEventListener("keydown",e=>{const k=map[e.key];if(k){e.preventDefault();keys.add(k)}});window.addEventListener("keyup",e=>{const k=map[e.key];if(k){e.preventDefault();keys.delete(k)}});c.querySelectorAll("[data-key]").forEach(btn=>{const k=btn.dataset.key;const press=e=>{e.preventDefault();keys.add(k);beep(260,.035,"square",.02)},release=e=>{e.preventDefault();keys.delete(k)};btn.addEventListener("pointerdown",press);btn.addEventListener("pointerup",release);btn.addEventListener("pointercancel",release);btn.addEventListener("pointerleave",release)});input.keys=keys}
function resizeCanvas(canvas){const dpr=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(320,Math.floor(r.width*dpr));canvas.height=Math.max(360,Math.floor(r.height*dpr));const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);return{w:r.width,h:r.height,ctx}}
function bg(ctx,w,h,road=false){ctx.fillStyle="#080c14";ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(120,150,190,.08)";for(let x=0;x<w;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(road){ctx.fillStyle="#171a20";ctx.fillRect(w*.18,0,w*.64,h);ctx.strokeStyle="#d0b24a";ctx.setLineDash([28,24]);ctx.lineWidth=4;for(const x of [w*.39,w*.61]){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}ctx.setLineDash([])}}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);const rand=(a,b)=>a+Math.random()*(b-a);
function finishMatch(win,score,note=""){if(!activeGame)return;const k=activeGame.k;activeGame=null;stopMusic();state.stats.matches++;if(win){state.stats.wins++;state.coins+=100+Math.floor(score/25);state.xp+=60+Math.floor(score/20);state.missionsDone=Math.min(1,state.missionsDone+1);beep(880,.18,"triangle",.05);setTimeout(()=>beep(1175,.22,"triangle",.04),90)}else{state.stats.losses++;state.coins+=25;state.xp+=15;beep(130,.22,"sawtooth",.035)}state.stats.bestScore=Math.max(state.stats.bestScore,Math.floor(score));while(state.xp>=state.level*250){state.xp-=state.level*250;state.level++}const ranks=["Bronze I","Bronze II","Bronze III","Silver I","Silver II","Gold I","Gold II","Platinum I"];state.rank=ranks[Math.min(ranks.length-1,Math.floor(state.level/2))];save();const root=document.getElementById("matchRoot");if(!root)return;root.innerHTML=`<div style="margin:auto;max-width:520px;width:calc(100% - 36px);padding:26px;background:#111722;border:1px solid #303a50;border-radius:22px;text-align:center"><div style="font-size:52px">${win?"🏆":"💀"}</div><h1>${win?"VICTORY":"MATCH OVER"}</h1><p style="opacity:.75">${esc(note||(win?"Great run. Rewards have been added.":"Keep training and try again."))}</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:20px 0"><div style="padding:14px;border-radius:14px;background:#0a0e16"><b>${Math.floor(score)}</b><small style="display:block;opacity:.6">Score</small></div><div style="padding:14px;border-radius:14px;background:#0a0e16"><b>${state.coins}</b><small style="display:block;opacity:.6">Coins</small></div></div><button id="resultLobby" class="button" style="width:100%">Return to Lobby</button></div>`;document.getElementById("resultLobby").onclick=()=>nav("lobby",k)}
function startMatch(k,m){const g=games[k],mode=g.modes.find(x=>x[0]===m)||[m,m,""];const ui=matchShell(g,mode);activeGame={k,m,g,mode,ui,started:performance.now()};document.getElementById("quitMatch").onclick=()=>{activeGame=null;stopMusic();nav("lobby",k)};document.getElementById("soundMatch").onclick=()=>{state.sound=!state.sound;save();document.getElementById("soundMatch").textContent=state.sound?"🔊":"🔇";if(state.sound)beep(600,.08)};ensureAudio();startMusic();if(g.type==="combat")runCombat(activeGame);else if(g.type==="racing")runRacing(activeGame);else if(g.type==="runner")runRunner(activeGame);else if(g.type==="fighter")runFighter(activeGame);else if(g.type==="sports")runSports(activeGame);else runHunt(activeGame)}

function runCombat(game){const {canvas,stats}=game.ui,{ctx}=resizeCanvas(canvas),input={};setupControls("combat",input);let p={x:canvas.clientWidth/2,y:canvas.clientHeight*.72,hp:100,max:100,ammo:12,maxAmmo:12,cool:0,heal:2},enemies=Array.from({length:game.m==="br"?10:6},()=>({x:rand(25,canvas.clientWidth-25),y:rand(90,canvas.clientHeight*.55),hp:50,max:50,cd:rand(.3,1.5),spd:rand(18,35)})),allies=game.m==="br"||game.m==="cs"?Array.from({length:3},(_,i)=>({x:canvas.clientWidth/2+(i-1)*45,y:canvas.clientHeight*.78,hp:80})):[];let bullets=[],score=0,kills=0,last=performance.now(),spawn=0,lock=0;
function shoot(){if(p.cool>0||p.ammo<=0)return;p.ammo--;p.cool=.18;beep(650,.045,"square",.025);const t=enemies.filter(e=>e.hp>0).sort((a,b)=>dist(p,a)-dist(p,b))[0]||{x:p.x,y:p.y-100},dx=t.x-p.x,dy=t.y-p.y,l=Math.hypot(dx,dy)||1;bullets.push({x:p.x,y:p.y,vx:dx/l*500,vy:dy/l*500,life:1})}function frame(now){if(!activeGame)return;const dt=Math.min(.035,(now-last)/1000);last=now;spawn+=dt;lock-=dt;const w=canvas.clientWidth,h=canvas.clientHeight;if(input.keys.has("a")&&lock<=0){shoot();lock=.12}if(input.keys.has("b")&&lock<=0){p.ammo=p.maxAmmo;lock=.5;beep(340,.14,"square",.025)}if(input.keys.has("c")&&lock<=0&&p.heal>0&&p.hp<p.max){p.heal--;p.hp=Math.min(p.max,p.hp+35);lock=.5;beep(520,.2)}let dx=(input.keys.has("right")?1:0)-(input.keys.has("left")?1:0),dy=(input.keys.has("down")?1:0)-(input.keys.has("up")?1:0),l=Math.hypot(dx,dy)||1;p.x=clamp(p.x+dx/l*210*dt,20,w-20);p.y=clamp(p.y+dy/l*210*dt,75,h-55);p.cool=Math.max(0,p.cool-dt);bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt});bullets=bullets.filter(b=>b.life>0&&b.x>-20&&b.x<w+20&&b.y>50&&b.y<h+20);enemies.forEach(e=>{if(e.hp<=0)return;const ex=p.x-e.x,ey=p.y-e.y,d=Math.hypot(ex,ey)||1;if(d>170){e.x+=ex/d*e.spd*dt;e.y+=ey/d*e.spd*dt}e.cd-=dt;if(e.cd<=0&&d<310){p.hp-=rand(2,5);e.cd=rand(.7,1.6)}});bullets.forEach(b=>enemies.forEach(e=>{if(e.hp>0&&dist(b,e)<18){e.hp-=25;b.life=0;if(e.hp<=0){kills++;score+=100;beep(760,.07)}}}));if(spawn>6&&enemies.filter(e=>e.hp>0).length<5&&game.m==="survival"){spawn=0;enemies.push({x:rand(25,w-25),y:rand(80,h*.45),hp:55,max:55,cd:1,spd:rand(22,40)})}score+=dt*5;ctx.clearRect(0,0,w,h);bg(ctx,w,h);allies.forEach(a=>{ctx.fillStyle="#48a8ff";ctx.beginPath();ctx.arc(a.x,a.y,13,0,Math.PI*2);ctx.fill()});enemies.forEach(e=>{if(e.hp<=0)return;ctx.fillStyle="#ef5364";ctx.beginPath();ctx.arc(e.x,e.y,15,0,Math.PI*2);ctx.fill();ctx.fillStyle="#111";ctx.fillRect(e.x-16,e.y-24,32,4);ctx.fillStyle="#55d66f";ctx.fillRect(e.x-16,e.y-24,32*(e.hp/e.max),4)});bullets.forEach(b=>{ctx.fillStyle="#ffd34e";ctx.beginPath();ctx.arc(b.x,b.y,4,0,Math.PI*2);ctx.fill()});ctx.fillStyle="#55d66f";ctx.beginPath();ctx.arc(p.x,p.y,17,0,Math.PI*2);ctx.fill();stats.textContent=`❤️ ${Math.max(0,Math.ceil(p.hp))} • 🔫 ${p.ammo}/${p.maxAmmo} • 🎯 ${kills} KOs • ⭐ ${Math.floor(score)}`;if(p.hp<=0){finishMatch(false,score,"Your squad was eliminated.");return}if(enemies.filter(e=>e.hp>0).length<=(game.m==="br"?0:1)){finishMatch(true,score+kills*50,"All hostile AI have been cleared.");return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

function runRacing(game){const {canvas,stats}=game.ui,{ctx}=resizeCanvas(canvas),input={};setupControls("racing",input);let w=canvas.clientWidth,h=canvas.clientHeight,p={x:w/2,y:h*.78,speed:225,boost:100,health:100},cars=Array.from({length:5},(_,i)=>({x:w*(.25+i*.12),y:rand(-500,-80),speed:rand(170,245)})),obs=[],distance=0,score=0,last=performance.now(),spawn=0,lock=0;function frame(now){if(!activeGame)return;const dt=Math.min(.035,(now-last)/1000);last=now;spawn+=dt;lock-=dt;w=canvas.clientWidth;h=canvas.clientHeight;const l=w*.18,r=w*.82,dx=(input.keys.has("right")?1:0)-(input.keys.has("left")?1:0);p.x=clamp(p.x+dx*280*dt,l+20,r-20);const boost=input.keys.has("a")&&p.boost>0;p.boost=clamp(p.boost+(boost?-35:12)*dt,0,100);p.speed=boost?320:225;distance+=p.speed*dt;score+=dt*(boost?18:10);cars.forEach(c=>{c.y+=c.speed*dt;if(c.y>h+70){c.y=rand(-500,-80);c.x=l+rand(20,r-l-20);score+=20}});if(spawn>.75){spawn=0;obs.push({x:l+rand(20,r-l-20),y:-30,size:rand(18,30)})}obs.forEach(o=>o.y+=p.speed*dt);obs=obs.filter(o=>o.y<h+50);const hit=obs.find(o=>Math.abs(o.x-p.x)<o.size+16&&Math.abs(o.y-p.y)<o.size+24);if(hit){p.health-=30;obs=obs.filter(o=>o!==hit);beep(110,.12,"sawtooth",.03)}ctx.clearRect(0,0,w,h);bg(ctx,w,h,true);cars.forEach(c=>{ctx.fillStyle="#d65a68";ctx.fillRect(c.x-13,c.y-25,26,50)});obs.forEach(o=>{ctx.fillStyle="#e6a33c";ctx.beginPath();ctx.arc(o.x,o.y,o.size,0,Math.PI*2);ctx.fill()});ctx.fillStyle="#55d66f";ctx.fillRect(p.x-15,p.y-28,30,56);stats.textContent=`❤️ ${Math.max(0,p.health)} • ⚡ ${Math.floor(p.boost)}% • 📏 ${Math.floor(distance)}m • ⭐ ${Math.floor(score)}`;const goal=game.m==="time"?120:900;if(p.health<=0){finishMatch(false,score,"Your vehicle was disabled.");return}if(distance>=goal){finishMatch(true,score+Math.max(0,1000-(performance.now()-game.started)/1000*4),"Finish line reached.");return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

function runRunner(game){const {canvas,stats}=game.ui,{ctx}=resizeCanvas(canvas),input={};setupControls("runner",input);let w=canvas.clientWidth,h=canvas.clientHeight,p={x:w*.24,y:h*.72,vy:0,ground:true,score:0,coins:0},obs=[],last=performance.now(),spawn=0,time=0,lock=0;function jump(){if(p.ground){p.vy=-600;p.ground=false;beep(520,.08,"triangle",.025)}}function frame(now){if(!activeGame)return;const dt=Math.min(.035,(now-last)/1000);last=now;time+=dt;spawn+=dt;lock-=dt;w=canvas.clientWidth;h=canvas.clientHeight;if(input.keys.has("a")&&lock<=0){jump();lock=.2}p.vy+=1450*dt;p.y+=p.vy*dt;if(p.y>=h*.72){p.y=h*.72;p.vy=0;p.ground=true}const speed=280+Math.min(180,time*5);if(spawn>.8){spawn=0;obs.push({x:w+30,y:h*.72,w:rand(22,42),h:rand(25,55),coin:Math.random()<.15})}obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x>-80);obs.forEach(o=>{if(o.coin&&Math.abs(o.x-p.x)<28&&Math.abs(o.y-p.y)<40){o.x=-100;p.coins++;p.score+=50;beep(850,.05)}});const hit=obs.find(o=>!o.coin&&o.x<p.x+18&&o.x+o.w>p.x-18&&o.y-o.h<p.y+20&&o.y>p.y-30);if(hit){finishMatch(false,p.score,"You hit an obstacle.");return}p.score+=dt*12;ctx.clearRect(0,0,w,h);bg(ctx,w,h);ctx.fillStyle="#192438";ctx.fillRect(0,h*.72+20,w,4);obs.forEach(o=>{if(o.coin){ctx.fillStyle="#ffd34e";ctx.beginPath();ctx.arc(o.x,o.y-20,12,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle="#ef5364";ctx.fillRect(o.x,o.y-o.h,o.w,o.h)}});ctx.fillStyle="#58d5ff";ctx.beginPath();ctx.arc(p.x,p.y,19,0,Math.PI*2);ctx.fill();stats.textContent=`🏃 ${Math.floor(time)}s • 🪙 ${p.coins} • ⭐ ${Math.floor(p.score)}`;if(game.m==="time"&&time>=45){finishMatch(true,p.score,"Time challenge completed.");return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

function runFighter(game){const {canvas,stats}=game.ui,{ctx}=resizeCanvas(canvas),input={};setupControls("fighter",input);let w=canvas.clientWidth,h=canvas.clientHeight,p={x:w*.30,y:h*.66,hp:100,cd:0,combo:0},e={x:w*.70,y:h*.66,hp:100,cd:1,block:false},last=performance.now(),time=0,lock=0,score=0;function attack(){if(p.cd>0)return;p.cd=.45;p.combo++;beep(600+p.combo*35,.07,"square",.025);if(Math.abs(p.x-e.x)<105&&!e.block){e.hp-=12+p.combo*2;score+=30}}function frame(now){if(!activeGame)return;const dt=Math.min(.035,(now-last)/1000);last=now;time+=dt;lock-=dt;p.cd=Math.max(0,p.cd-dt);if(input.keys.has("a")&&lock<=0){attack();lock=.18}const block=input.keys.has("c");let dx=(input.keys.has("right")?1:0)-(input.keys.has("left")?1:0);p.x=clamp(p.x+dx*180*dt,35,w-35);const d=p.x-e.x;e.block=Math.abs(d)<95&&Math.random()<.08;if(Math.abs(d)>90)e.x+=Math.sign(d)*70*dt;else{e.cd-=dt;if(e.cd<=0){e.cd=rand(.6,1.2);if(!block){p.hp-=rand(7,12);score=Math.max(0,score-10);beep(120,.07,"sawtooth",.02)}}}ctx.clearRect(0,0,w,h);bg(ctx,w,h);ctx.fillStyle="#55d66f";ctx.beginPath();ctx.arc(p.x,p.y,28,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ef5364";ctx.beginPath();ctx.arc(e.x,e.y,28,0,Math.PI*2);ctx.fill();if(block){ctx.strokeStyle="#6fd7ff";ctx.lineWidth=7;ctx.beginPath();ctx.arc(p.x,p.y,37,0,Math.PI*2);ctx.stroke()}ctx.fillStyle="#111";ctx.fillRect(20,25,w*.38,10);ctx.fillStyle="#55d66f";ctx.fillRect(20,25,w*.38*(Math.max(0,p.hp)/100),10);ctx.fillStyle="#111";ctx.fillRect(w-20-w*.38,25,w*.38,10);ctx.fillStyle="#ef5364";ctx.fillRect(w-20-w*.38,25,w*.38*(Math.max(0,e.hp)/100),10);stats.textContent=`❤️ ${Math.ceil(p.hp)} • 👊 Combo ${p.combo} • ⭐ ${Math.floor(score)}`;if(e.hp<=0){finishMatch(true,score+200,"Opponent defeated.");return}if(p.hp<=0){finishMatch(false,score,"You were knocked out.");return}if(game.m==="training"&&time>=45){finishMatch(true,score+100,"Training complete.");return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

function runSports(game){const {canvas,stats}=game.ui,{ctx}=resizeCanvas(canvas),input={};setupControls("sports",input);let w=canvas.clientWidth,h=canvas.clientHeight,p={x:w*.25,y:h*.55,score:0},ball={x:w*.5,y:h*.55,vx:0,vy:0,owner:"player"},ai={x:w*.75,y:h*.55},last=performance.now(),time=0,lock=0;const basketball=game.k==="hoops";function action(){if(lock>0)return;lock=.6;if(ball.owner==="player"){const gx=basketball?w*.86:w*.92;ball.owner="free";ball.x=p.x;ball.y=p.y;ball.vx=(gx-p.x)*2;ball.vy=(h*.5-p.y)*2;beep(720,.08,"triangle",.025)}else if(dist(p,ball)<45){ball.owner="player";beep(480,.05)}}function frame(now){if(!activeGame)return;const dt=Math.min(.035,(now-last)/1000);last=now;time+=dt;lock=Math.max(0,lock-dt);if(input.keys.has("a"))action();let dx=(input.keys.has("right")?1:0)-(input.keys.has("left")?1:0),dy=(input.keys.has("down")?1:0)-(input.keys.has("up")?1:0),l=Math.hypot(dx,dy)||1;p.x=clamp(p.x+dx/l*200*dt,20,w-20);p.y=clamp(p.y+dy/l*200*dt,100,h-45);ai.x+=(p.x-ai.x)*.35*dt;ai.y+=(p.y-ai.y)*.35*dt;if(ball.owner==="player"){ball.x=p.x;ball.y=p.y}else if(ball.owner==="free"){ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.vx*=.98;ball.vy*=.98;if(dist(p,ball)<28){ball.owner="player";beep(500,.05)}}const gx=basketball?w*.86:w*.92;if(ball.x>gx-15){p.score+=basketball?2:1;ball={x:w*.5,y:h*.55,vx:0,vy:0,owner:"player"};beep(900,.12,"triangle",.04)}if(ball.owner==="player"&&dist(ai,p)<35){ball.owner="free";ball.x=p.x;ball.y=p.y;ball.vx=-170;ball.vy=rand(-70,70)}ctx.clearRect(0,0,w,h);bg(ctx,w,h);ctx.strokeStyle="#52617d";ctx.lineWidth=4;ctx.strokeRect(18,90,w-36,h-125);ctx.fillStyle="#55d66f";ctx.beginPath();ctx.arc(p.x,p.y,22,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ef5364";ctx.beginPath();ctx.arc(ai.x,ai.y,22,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ffd34e";ctx.beginPath();ctx.arc(ball.x,ball.y,10,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="bold 18px sans-serif";ctx.fillText(basketball?"🏀 HOOP":"⚽ GOAL",gx-55,115);stats.textContent=`${basketball?"🏀":"⚽"} Score ${p.score} • ⏱️ ${Math.max(0,Math.ceil(60-time))}s`;if((game.m==="penalty"||game.m==="shootout")&&p.score>=3){finishMatch(true,p.score*100,"Challenge won.");return}if(time>=60){finishMatch(p.score>0,p.score*100,p.score>0?"You scored!":"The match ended.");return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

function runHunt(game){const {canvas,stats}=game.ui,{ctx}=resizeCanvas(canvas),input={};setupControls("hunt",input);let w=canvas.clientWidth,h=canvas.clientHeight,p={x:w*.5,y:h*.78,hp:100,ammo:10},targets=[],score=0,hit=0,time=0,last=performance.now(),spawn=0,lock=0;function fire(){if(lock>0||p.ammo<=0)return;lock=.25;p.ammo--;beep(760,.05,"square",.025);const t=targets.filter(x=>x.hp>0).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(t&&dist(p,t)<Math.min(w,h)*.65){t.hp=0;hit++;score+=100;beep(980,.06,"triangle",.03)}}function frame(now){if(!activeGame)return;const dt=Math.min(.035,(now-last)/1000);last=now;time+=dt;spawn+=dt;lock=Math.max(0,lock-dt);if(input.keys.has("a"))fire();if(input.keys.has("b")&&p.ammo<10){p.ammo=10;beep(330,.12,"square",.02)}let dx=(input.keys.has("right")?1:0)-(input.keys.has("left")?1:0),dy=(input.keys.has("down")?1:0)-(input.keys.has("up")?1:0),l=Math.hypot(dx,dy)||1;p.x=clamp(p.x+dx/l*150*dt,25,w-25);p.y=clamp(p.y+dy/l*150*dt,100,h-35);if(spawn>.65){spawn=0;targets.push({x:rand(35,w-35),y:rand(110,h*.62),hp:1,life:rand(2,5)})}targets.forEach(t=>t.life-=dt);targets=targets.filter(t=>t.hp>0&&t.life>0);if(game.k==="tactical"&&targets.length>6)p.hp-=dt*3;ctx.clearRect(0,0,w,h);bg(ctx,w,h);targets.forEach(t=>{ctx.fillStyle=game.k==="archery"?"#e9b54d":"#ef5364";ctx.beginPath();ctx.arc(t.x,t.y,18,0,Math.PI*2);ctx.fill();ctx.fillStyle="#10151f";ctx.beginPath();ctx.arc(t.x,t.y,7,0,Math.PI*2);ctx.fill()});ctx.strokeStyle="#6bd5ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,22,0,Math.PI*2);ctx.stroke();stats.textContent=`❤️ ${Math.ceil(p.hp)} • 🎯 ${hit} hits • 🔫 ${p.ammo}/10 • ⭐ ${Math.floor(score)}`;if(p.hp<=0){finishMatch(false,score,"Mission failed.");return}if(hit>=10){finishMatch(true,score+250,"Objective complete.");return}if((game.m==="time"||game.m==="range")&&time>=45){finishMatch(hit>=5,score,"Time challenge complete.");return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

function render(route,extra=""){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.route===route));let html="";if(route==="home")html=home();else if(route==="games")html=gamesPage();else if(route==="lobby")html=gameLobby(extra);else if(route==="mode")html=modePreview(...extra.split(":"));else if(route==="missions")html=missions();else if(route==="rewards")html=rewards();else if(route==="earn")html=earn();else if(route==="leaderboard")html=leaderboard();else if(route==="profile")html=profile();else if(route==="shop")html=shop();else if(route==="garage")html=garage();else if(route==="controls")html=controls();else html=home();screen.innerHTML=html}

document.addEventListener("click",e=>{
  const route=e.target.closest("[data-route]")?.dataset.route;if(route){nav(route);return}
  if(e.target.closest("[data-action='home']")){nav("home");return}
  if(e.target.closest("[data-action='profile']")){nav("profile");return}
  if(e.target.closest("[data-action='back']")){back();return}
  const game=e.target.closest("[data-game]")?.dataset.game;if(game){nav("lobby",game);return}
  const gm=e.target.closest("[data-game-mode]");if(gm){nav("mode",gm.dataset.gameMode+":"+gm.closest("[data-mode]").dataset.mode);return}
  const mode=e.target.closest("[data-mode]")?.dataset.mode;if(mode){nav("mode","competitive:"+mode);return}
  const start=e.target.closest("[data-start]")?.dataset.start;if(start){const [k,m]=start.split("/");startMatch(k,m);return}
  if(e.target.closest("[data-daily]")&&!state.claimedDaily){state.coins+=100;state.claimedDaily=true;save();beep(700,.1);render("rewards");return}
  const buy=e.target.closest("[data-buy]")?.dataset.buy;
  if(buy==="character"&&state.coins>=500){state.coins-=500;if(!state.owned.characters.includes("Nova"))state.owned.characters.push("Nova");save();render("shop");alert("Character purchased.");return}
  if(buy==="car"&&state.coins>=800){state.coins-=800;if(!state.owned.cars.includes("Velocity X"))state.owned.cars.push("Velocity X");save();render("shop");alert("Vehicle purchased.");return}
  if(e.target.closest("[data-gem-buy]")&&state.gems>=50){state.gems-=50;save();render("shop");alert("Premium item purchased.");return}
  const car=e.target.closest("[data-equip-car]")?.dataset.equipCar;if(car){state.equipped.car=car;save();render("garage");return}
  const control=e.target.closest("[data-control]")?.dataset.control;if(control){state.controlScheme=control;localStorage.setItem("mars_control_scheme",control);save();alert(control+" controls selected.");return}
  if(e.target.closest("[data-toggle-sound]")){state.sound=!state.sound;save();render("profile");return}
});

function startLoading(){let p=0;const bar=document.getElementById("loadingBar"),txt=document.getElementById("loadingText"),loading=document.getElementById("loading"),app=document.getElementById("app");if(!bar||!txt){if(app)app.hidden=false;const parts=location.hash.slice(1).split("/");render(parts[0]||"home",parts[1]||"");return}const timer=setInterval(()=>{p=Math.min(100,p+Math.floor(Math.random()*9)+3);bar.style.width=p+"%";txt.textContent="LOADING "+p+"%";if(p>=100){clearInterval(timer);setTimeout(()=>{if(loading)loading.remove();if(app)app.hidden=false;const parts=location.hash.slice(1).split("/");render(parts[0]||"home",parts[1]||"")},250)}},70)}
startLoading();
